name: 05 - Filters - Activity Types

on:
  pull_request:
    types: [closed]]
  branch:
    - main
  
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo the trigger
        run: echo "Running whenever a PR is closed."
        
