name: 06 - Contexts

on:
  workflow_dispatch:
  
jobs:
  echo-data:
    runs-on: ubuntu-latest
    steps:
      - name: Display Information
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run Number: ${{ github.run_number }}"
          echo "Job: ${{ github.job }}"
          echo "Workflow Path: ${{ github.workflow_path }}"
          echo "Event Payload: ${{ toJson(github.event) }}"
      - name: Retrieve Variable
        run: |
          echo "The value of MY_VARIABLE is: ${{ vars.MY_VARIABLE }}"
